config/routes.rb
Rails.application.routes.draw do

  resources :invitations
  resources :event_items
  resources :items
  resources :events
  devise_for :users

  delete 'exit_event/:id', to: 'events#exit_event', as: 'exit_event'
  get 'participating', to: 'events#participating', as: 'participating'
  get 'configs', to: 'user#configs', as: 'user_configs'
  patch 'configs', to: 'user#upload_avatar'
  get 'accept/invitation/:id', to: 'invitations#accept', as: 'accept_invities'
  get 'viewed_invitation/:id', to: 'invitations#viewed_invitation', as: 'viewed_invitation'
  patch 'event_item_status/:id', to: 'event_items#charge_status', as: 'charge_status'
  root to: 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
        resources :users, only: [:show, :create, :update, :destroy]
        resources :invitations
        resources :event_items
        resources :items
        resources :events
        get 'participating', to: 'events#participating'
        get 'configs', to: 'user#configs'
        patch 'configs', to: 'user#upload_avatar'
        get 'accept/invitation/:id', to: 'invitations#accept'
        get 'viewed_invitation/:id', to: 'invitations#viewed_invitation'
        get '/', to:'dashboard#index'
    end
  end
end

app/controllers/api/v1/dashboard_controller.rb
# frozen_string_literal: true
module Api
  module V1
    class DashboardController < BaseController
      before_action :authenticate_user!

      def index
        data_rray = []
        data = {}
        events_all = EventUser.where(user_id: current_user).all
        events_all.each do |events|
          data = {
            id: events.event.id,
            description: events.event.description,
            created_at: events.event.created_at,
            user: events.event.user.name,
            total: events.event.total,
            items: events.event.select_item_by_events(events.event.id).count
          }
        data_rray << data
        end
          render json: { event: data_rray }
      end
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @events_all = EventUser.where(user_id: current_user.id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="m-b-2">
    <div class="container">
        <div class="row">
            <div class="col-8 m-auto text-dark p-t-40 p-b-90">
                <div class="card">
                  <div class="form-group col-12">
                    <p class="p-t-30 form-dark ">
                        <input type="search" placeholder="Busque por eventos" class="form-control text-dark form-control-lg" id="search">
                    </p>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12">
  <div class="card m-b-10">
    <div class="card-header">
      <h5 class="m-b-0 h2">
          <i class="mdi mdi-checkbox-intermediate"></i> Meus eventos
      </h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover align-td-middle">
        <thead class="text-center">
        <tr class="h3">
          <th>Evento</th>
          <th>Data</th>
          <th>Item</th>
          <th>Total</th>
          <th>Ação</th>
        </tr>
        </thead>
        <tbody class="text-center">
          <% @events_all.each do |all_event|%>
            <tr class="h4 text">
              <td>
                <%= all_event.event.description%>
              </td>
              <td>
                <%= all_event.event.data_event%>
              </td>
              <td>
                <%= all_event.event.select_item_by_events(all_event.event.id).count%>
              </td>
              <td>
                <% if all_event.event.total.present?  %>
                  <%= number_to_currency_br(all_event.event.total)%>
                <% else %>
                  R$ 00,00
                <% end %>
              </td>
              <td class="text-center">
                <% if all_event.event.user.id == current_user %>
                <%= link_to '<i class="mdi mdi-eye"></i>'.html_safe, event_path(all_event.event_id), class:'btn btn-primary'%>
                <%= link_to '<i class="mdi mdi-trash-can-outline"></i>'.html_safe, all_event.event, method: :delete, class:'btn btn-danger' %>
                <% else %>
                <%= link_to '<i class="mdi mdi-eye"></i>'.html_safe, event_path(all_event.event_id), class:'btn btn-primary'%>
                <%= link_to '<i class="mdi mdi-exit-run"></i>'.html_safe, exit_event_url(all_event.event), method: :delete, class:'btn btn-warning' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        </table>
      </div>
    <div class="col-md-12"></div>
  </div>
</div>