config/routes.rb
Rails.application.routes.draw do

  resources :invitations
  resources :event_items
  resources :items
  resources :events
  devise_for :users

  delete 'exit_event/:id', to: 'events#exit_event', as: 'exit_event'
  get 'participating', to: 'events#participating', as: 'participating'
  get 'configs', to: 'user#configs', as: 'user_configs'
  patch 'configs', to: 'user#upload_avatar'
  get 'accept/invitation/:id', to: 'invitations#accept', as: 'accept_invities'
  get 'viewed_invitation/:id', to: 'invitations#viewed_invitation', as: 'viewed_invitation'
  patch 'event_item_status/:id', to: 'event_items#charge_status', as: 'charge_status'
  root to: 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
        resources :users, only: [:show, :create, :update, :destroy]
        resources :invitations
        resources :event_items
        resources :items
        resources :events
        get 'participating', to: 'events#participating'
        get 'configs', to: 'user#configs'
        patch 'configs', to: 'user#upload_avatar'
        get 'accept/invitation/:id', to: 'invitations#accept'
        get 'viewed_invitation/:id', to: 'invitations#viewed_invitation'
        get '/', to:'dashboard#index'
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates_presence_of :data_event
  validates_presence_of :description

  validate :verifi_name, on: :create

  def verifi_name
    namepresent = User.find(user_id)
    return if namepresent.name.present?

    errors.add(:base, ' você precisa inserir um apelido antes.')
  end

  def get_item_not_inclued(event_id,current_user)
    item_array = []
    event_items = Event.new.select_item_by_events(event_id)
    event_items.each do |item|
      item_array << item.item_id
    end
    Item.where(user_id: current_user).where.not(id: item_array)
  end

  def select_item_by_events(event_id)
    EventItem.where(event_id: event_id)
  end

  def delete_event(id)
    event_item = EventItem.where(event_id: id)
    event_item.delete_all
    event_user = EventUser.where(event_id: id)
    event_user.delete_all
  end

  def event_create
    t = Event.last
    user_events = EventUser.where(event_id: t.id)
    if user_events.present?
      return true
    else
      EventUser.create(event_id: t.id, user_id: t.user_id)
    end
  end
end

app/controllers/api/v1/events_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class EventsController < BaseController
      include DeviseTokenAuth::Concerns::SetUserByToken

      before_action :authenticate_user!


      before_action :set_event, only: %i[show edit update destroy]

      # GET /events
      # GET /events.json
      def index
        @events = Event.where(user_id: current_user.id)
      end

      def participating
        @event_users = EventUser.where(user_id: current_user.id)
      end

      # GET /events/1
      # GET /events/1.json
      def show
        permit_show
        data_array_event_item = []
        data = []
        @event_items = Event.new.select_item_by_events(params[:id])
        @items = Event.new.get_item_not_inclued(params[:id], current_user)
        @event_items.each do |event_item|
          print event_item.item.inspect
          data = {
            id: event_item.id,
            description: event_item.item.description,
            user: event_item.item.user.name,
            value: event_item.item.value,
            item_id: event_item.item.id,
            location: event_item.item.location,
            status: event_item.status
          }
        data_array_event_item << data
        end
        render json: { event_items: data_array_event_item, items: @items }
      end

      # GET /events/new
      def new
        @event = Event.new
      end

      # GET /events/1/edit
      def edit; end

      # POST /events
      # POST /events.json
      def create
        @event = Event.new(event_params.merge(user_id: current_user.id))
        if @event.save
          Event.new.event_create
          render json: { status: 200 }
        else
          render json: { status: @event.errors.full_messagers.to_sentence }
        end
      end

      # PATCH/PUT /events/1
      # PATCH/PUT /events/1.json
      def update
        respond_to do |format|
          if @event.update(event_params)
            format.html { redirect_to @event, notice: 'Event was successfully updated.' }
            format.json { render :show, status: :ok, location: @event }
          else
            format.html { render :edit }
            format.json { render json: @event.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /events/1
      # DELETE /events/1.json
      def destroy
        Event.new.delete_event(params[:id])
        @event.destroy
        flash[:error] = 'Evento removido'
        redirect_to root_path
      end

      def permit_show
        return if Event.where(id: set_event.id, user_id: current_user).present?

        flash[:error] = 'Não altorizado!'
        redirect_to root_path
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_event
        @event = Event.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def event_params
        params.permit(:description, :user_id, :data_event)
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(user_id: current_user.id)
  end


  def participating
    @event_users = EventUser.where(user_id: current_user.id)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    permit_show
    @event_item = EventItem.new
    @event_items = Event.new.select_item_by_events(params[:id])
    @items = Event.new.get_item_not_inclued(params[:id],current_user)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.merge(user_id: current_user.id))
    if @event.save
      Event.new.event_create
      flash[:success] =  "Evento criado!"
      redirect_to root_path
    else
      flash[:error] =  @event.errors.full_messages.to_sentence
      redirect_to root_path
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    Event.new.delete_event(params[:id])
    @event.destroy
    flash[:error] = 'Evento removido'
    redirect_to root_path
  end

  def exit_event
    event_user = EventUser.where(user_id: current_user, event_id: params[:id]).take
    event_user.destroy
    flash[:error] = 'Saida do evento realizada!'
    redirect_to root_path
  end

  def permit_show
    return if EventUser.where(event_id: set_event.id, user_id: current_user).present?

    flash[:error] = 'Não altorizado!'
    redirect_to root_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:description, :user_id,:data_event)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, class:'form-dark') do |form| %>
  <div class="form-row">
    <div class="form-group  col-md-9">
      <%= form.label :description %>
      <%= form.text_field :description, class:'form-control form-control-lg text-description' %>
    </div>
     <div class="form-group  col-md-3">
      <%= form.label :"Data do evento" %>
      <%= form.text_field :data_event, class:'form-control form-control-lg timedate', placeholder: 'dd/mm/aaaa 00:00' %>
    </div>
  </div>
  <div class="text-center">
    <%= form.submit 'Criar evento', class:'btn btn-lg m-b-15 ml-2 mr-2 btn-success' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/new.html.erb
<div class="container p-t-100 p-b-50  m-b-30">
  <div class="row">
    <div class="col-lg-12">
      <div class="card m-b-30 bg-dark text-white">
        <div class="card-body ">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/participating.html.erb
<p id="notice"><%= notice %></p>

<h1>Participando</h1>

<table>
  <thead>
    <tr>
      <th>Criador</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_users.each do |event_user| %>
      <tr>
        <td><%= event_user.event.user.email %></td>
        <td><%= event_user.event.description %></td>
        <td><%= link_to 'Show', event_user.event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/show.html.erb
<div class=" bg-event m-b-30 bg-stars">
 <div class="container">
    <div class="row">
      <div class="col-md-8 m-auto text-dark p-t-40 p-b-90">
        <h1><span class="js-greeting">Evento</span>, <%= @event.description.capitalize %>.</h1>
        <p class="opacity-75">
          Criado em <%= @event.created_at %> por <%= @event.user.name %>
        </p>
          <p class="opacity-75">
          Dia do evento <%= @event.data_event %>
        </p>
      </div>
      <div class="col-md-4 m-auto text-white p-t-40 p-b-90">
        <div class="text-md-right">
          <div class="">
            <p>
              <button type="button" class="btn btn-lg m-b-15 ml-2 mr-2 btn-primary" data-toggle="modal" data-target="#slideRightModal">
                Participantes
              </button>
                <button type="button" class="btn btn-lg m-b-15 ml-2 mr-2  btn-white" data-toggle="modal" data-target="#new-item-event">
                <i class="mdi mdi-plus"></i> Item
              </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container pull-up">
  <div class="row mx-md-n2">
  <% @event_items.each do |event_item| %>
    <div class="col-lg-3 col-md-6 m-b-30">
      <div class="card card-hover">
        <div class="card-body">
          <div class="text-center ">
              <h2 class="fw-600 p-t-20"><%= event_item.item.description.capitalize %></h2>
              <div class="text-center">
                <div class=" h3 fw-500">
                  <p class="text-muted fw-600"><%= event_item.item.location.capitalize %></p>
                </div>
                <div class=" h3 fw-500">
                  <p class="text-muted fw-600"><%= event_item.quantities %> quantidades</p>
                </div>
                <div class=" h3 fw-500">
                <p class="text-muted fw-600">
                <% if event_item.status %>
                  <div class="text-success h6 fw-500">
                    Comprado
                  </div>
                <% else %>
                  <div class="text-danger h6 fw-500">
                    Não comprado
                  </div>
                <% end %>
                </p>
                </div>
                <div class="text-success h5 fw-600">
                <%= number_to_currency_br(event_item.item.value*event_item.quantities) %>
                <br>
                <br>
                <% if event_item.status %>
                  <div class="col-md-12">
                    <%= link_to '<i class="mdi mdi-backup-restore"></i>'.html_safe, charge_status_path(event_item,item_id: event_item.item.id), method: :patch , class:'btn btn-lg  m-b-15 ml-2 mr-2 btn-white col-md-10' %>
                  </div>
                <% else %>
                <div class="row">
                  <div class="col-md-6">
                    <%= link_to '<i class="mdi mdi-cart-plus"></i>'.html_safe, charge_status_path(event_item,item_id: event_item.item.id), method: :patch, class:'btn btn-lg m-b-15 ml-2 mr-2 btn-success' %>
                  </div>
                  <div class="col-md-6">
                  <%= link_to '<i class="mdi mdi-trash-can"></i>'.html_safe, event_item_path(event_item.id), method: :delete, class:'btn btn-lg m-b-15 ml-2 mr-2 btn-danger'%>
                  </div>
                </div>
                 <% end %>
                <div class="h6 fw-500">
                <p class="text-muted fw-600"><%= event_item.item.user.name %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   <% end %>
  </div>
</div>

<div class="modal fade modal-slide-right" id="new-item-event" tabindex="-1" role="dialog" aria-labelledby="slideRightModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content-event">
      <div class="modal-header">
        <div class="form-dark">
          <div class="input-group input-group-flush mb-3">
            <input placeholder="Busque por nome do item" type="search" class="form-control form-control-lg search form-control-prepended" id="search">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="mdi mdi-magnify"></i>
                </div>
            </div>
          </div>
      </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="row m-b-90">
          <% @items.each do |item|%>
           <div class="col-lg-6 col-md-10 text" >
              <%= form_with(model: @event_item, local: true) do |form| %>
                <div class="card mt-3">
                <%= form.hidden_field(:event_id, value: params[:id])%>
                <%= form.hidden_field(:item_id , value: item.id)%>
                  <div class="card-body text-dark">
                    <h4 class="card-title"><%= item.description.capitalize %> <h4 class="text-success"><%= number_to_currency_br(item.value) %></h4></h4>
                    <%= form.text_field :quantities, class:'form-control form-control-lg', placeholder: 'Quantidade' %>
                  </div>
                </div>
                  <div class="text-center">
                    <%= form.button '<i class="mdi mdi-plus mdi-24px"></i>'.html_safe,  class:'btn btn-success col-md-12' %>
                  </div>
                <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade modal-slide-right" id="slideRightModal" tabindex="-1" role="dialog" aria-labelledby="slideRightModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content-event">
      <div class="modal-header">
        <h5 class="modal-title" id="slideRightModalLabel">Participantes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table align-td-middle table-card">
           <tbody>
          <% @event.select_users_by_events(params[:id]).each do |event_user|%>
            <tr>
              <td>
                <div class="avatar avatar-xl">

                   <%= image_tag event_user.user.avatar, class:'avatar-img rounded-circle' if event_user.user.avatar.attached? %>
                </div>
              </td>
              <td><%= event_user.user.name %></td>
              <td><%= event_user.user.email %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>