config/routes.rb
Rails.application.routes.draw do

  resources :invitations
  resources :event_items
  resources :items
  resources :events
  devise_for :users

  delete 'exit_event/:id', to: 'events#exit_event', as: 'exit_event'
  get 'participating', to: 'events#participating', as: 'participating'
  get 'configs', to: 'user#configs', as: 'user_configs'
  patch 'configs', to: 'user#upload_avatar'
  get 'accept/invitation/:id', to: 'invitations#accept', as: 'accept_invities'
  get 'viewed_invitation/:id', to: 'invitations#viewed_invitation', as: 'viewed_invitation'
  patch 'event_item_status/:id', to: 'event_items#charge_status', as: 'charge_status'
  root to: 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
        resources :users, only: [:show, :create, :update, :destroy]
        resources :invitations
        resources :event_items
        resources :items
        resources :events
        get 'participating', to: 'events#participating'
        get 'configs', to: 'user#configs'
        patch 'configs', to: 'user#upload_avatar'
        get 'accept/invitation/:id', to: 'invitations#accept'
        get 'viewed_invitation/:id', to: 'invitations#viewed_invitation'
        get '/', to:'dashboard#index'
    end
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validate :verify_if_user_exist_invite, on: :create

  def viewed_invitation(id)
    Invitation.where(id: id).update(viewed: true)
  end

  def verify_if_user_exist_invite
    invitation = Invitation.where(user_id: user_id).present?
    return if invitation == false

    errors.add(:base, 'Já foi encaminhado um convite para esta pessoa!')
  end

  def afte_accept
    last_invitation = Invitation.last
    event = Event.find(last_invitation.event_id)
    EventUser.create(user_id: last_invitation.user_id,event_id: event.id)
    last_invitation.delete
  end
end

app/controllers/api/v1/invitations_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class InvitationsController < BaseController
      include DeviseTokenAuth::Concerns::SetUserByToken

      before_action :authenticate_user!

      before_action :set_invitation, only: %i[show edit update destroy]

      # GET /invitations
      # GET /invitations.json
      def index
        @invitations = Invitation.where(user_id: current_user.id)
        @events = Event.where(user_id: current_user.id)
        @users = User.all
        @invitation = Invitation.new
      end

      # GET /invitations/1
      # GET /invitations/1.json
      def accept
        invite = Invitation.find(params[:id])
        if invite.update(accept: true)
          flash[:success] = 'Convite aceito!'
          Invitation.new.afte_accept
          redirect_to invitations_path
        else
          flash[:error] = invite.errors.full_messages.to_sentence
          redirect_to invitations_path
        end
      end

      def show
        permit_show
        @invitation_envites_users = Invitation.new.select_users_by_events(params[:id])
        Invitation.new.viewed_invitation(params[:id])
      end

      # GET /invitations/new
      def new; end

      # GET /invitations/1/edit
      def edit; end

      # POST /invitations
      # POST /invitations.json
      def create
        @invitation = Invitation.new(invitation_params.merge(viewed: false))
        if @invitation.save
          flash[:success] = 'Convite enviado'
          redirect_to invitations_path
        else
          flash[:error] = @invitation.errors.full_messages.to_sentence
          redirect_to invitations_path
        end
      end

      # PATCH/PUT /invitations/1
      # PATCH/PUT /invitations/1.json
      def update
        respond_to do |format|
          if @invitation.update(invitation_params)
            format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
            format.json { render :show, status: :ok, location: @invitation }
          else
            format.html { render :edit }
            format.json { render json: @invitation.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /invitations/1
      # DELETE /invitations/1.json
      def destroy
        @invitation.destroy
        flash[:success] = 'Convite aceito!'
        redirect_to invitations_path
      end

      def permit_show
        return if Invitation.where(id: set_invitation.id, user_id: current_user)

        flash[:error] = 'Não altorizado!'
        redirect_to root_path
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_invitation
        @invitation = Invitation.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def invitation_params
        params.require(:invitation).permit(:user_id, :accept, :event_id)
      end
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_invitation, only: [:show, :edit, :update, :destroy]

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.where(user_id: current_user.id)
    @events = Event.where(user_id: current_user.id)
    @users = User.all
    @invitation = Invitation.new
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def accept
    invite = Invitation.find(params[:id])
    if invite.update(accept: true)
      flash[:success] = 'Convite aceito!'
      Invitation.new.afte_accept
      redirect_to invitations_path
    else
      flash[:error] = invite.errors.full_messages.to_sentence
      redirect_to invitations_path
    end
  end

  def show
    permit_show
    @invitation_envites_users = Invitation.new.select_users_by_events(params[:id])
    Invitation.new.viewed_invitation(params[:id])
  end

  # GET /invitations/new
  def new

  end

  # GET /invitations/1/edit
  def edit

  end

  # POST /invitations
  # POST /invitations.json
  def create
    @invitation = Invitation.new(invitation_params.merge(viewed: false))
    if @invitation.save
      flash[:success] = 'Convite enviado'
      redirect_to invitations_path
    else
      flash[:error] = @invitation.errors.full_messages.to_sentence
      redirect_to invitations_path
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    flash[:success] = 'Convite aceito!'
    redirect_to invitations_path
  end

  def permit_show
    return if Invitation.where(id: set_invitation.id, user_id: current_user)

    flash[:error] = 'Não altorizado!'
    redirect_to root_path
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:user_id, :accept,:event_id)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_with(model: invitation, local: true) do |form| %>
<div class="form-group">
  <div class="input-group input-group-flush mb-3">
    <%= form.select :user_id, @users.collect { |u| [u.name, u.id] }, {:prompt => 'Selecione o convidado'},class:'form-control form-control-prepended select2'%>
     <div class="input-group-prepend">
      <div class="input-group-text">
        <span class=" mdi mdi-account "></span>
      </div>
    </div>
  </div>

  <div class="input-group input-group-flush mb-4">
    <%= form.select :event_id, @events.collect { |e| [e.description, e.id] },  {:prompt => 'Selecione o evento'},class:'form-control form-control-prepended select2' %>
      <div class="input-group-prepend">
        <div class="input-group-text">
          <span class="mdi mdi-diamond-stone"></span>
        </div>
      </div>
  </div>

  <div class="form-group">
    <%= form.submit 'Enviar', class:'btn text-uppercase btn-block  btn-primary' %>
  </div>
</div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<section class="admin-content " id="contact-search">
  <div class="bg-event m-b-30">
    <div class="container">
      <div class="row p-b-60 p-t-60">

        <div class="col-md-6 text-center mx-auto text-white p-b-30">
          <h1>Convites </h1>
        </div>
        <div class="col-md-6 text-center mx-auto text-white p-b-30">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#customModal">
            Enviar convite <i class="mdi mdi-send"></i>
          </button>
        </div>
      </div>
    </div>
  </div>

  <% if @invitations.present? %>
    <div class="container pull-up">
      <div class="row  m-b-90">
        <% @invitations.each do |invitation|%>
        <div class="col-lg-4 ">
          <%= link_to  invitation_path(invitation.id), class:'card shadow-lg guide-event ' do%>
          <div class="card-body text-dark">
            <h4 class="card-title">
              <%= invitation.event.user.name %> quer convida você para este evento, <%= invitation.event.description%>
            </h4>
            <p>Data do evento: <%= invitation.event.data_event%>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="container pull-up">
      <div class="row  m-b-90">
        <div class="col-lg-12 ">
          <div class="card shadow-lg guide-event ">
            <div class="card-body text-dark">
              <h1 class="card-title text-sm-center p-b-60 p-t-60">Sem convites no momento...</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</section>


<div class="modal fade " data-keyboard="false" id="customModal" tabindex="-1" role="dialog"
  aria-labelledby="customModal" aria-hidden="true">
  <div class="modal-dialog  modal-sm modal-dialog-centered" role="document">
    <div class="modal-content m-t-80">
      <div class="modal-body">
        <div class="">
          <h3 class="text-center">Envio de convites </h3>
          <%= render 'form', invitation: @invitation %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/invitations/new.html.erb
<h1>New Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Back', invitations_path %>

app/views/invitations/show.html.erb
<section class="admin-content ">
  <div class="bg-dark m-b-30">
    <div class="container">
      <div class="row p-b-60 p-t-60">
        <div class="col-md-6 text-white p-b-30">
          <div class="media">
            <div class="avatar avatar mr-3">
              <div class="avatar-title bg-success rounded-circle mdi mdi-receipt  ">
              </div>
            </div>
            <div class="media-body">
              <div class="opacity-75">Para,</div>
              <h4 class="m-b-0"><%= @invitation.user.name %></h4>
              <p class="opacity-75">
                Convite de <%= @invitation.event.user.name %> <br>
                Data do Convite : <%= @invitation.created_at %>
              </p>
              </div>
            </div>

          </div>
          <div class="col-md-5 text-center m-b-30 ml-auto">
            <div class="rounded text-white bg-white-translucent">
              <div class="p-all-15">
                <div class="row">
                  <div class="col-md-6 my-2 m-md-0">
                    <%= link_to  accept_invities_path(@invitation.id) do %>
                     <h3 class="mdi mdi-check-outline"></h3>
                      <div class="text-overline text-success">
                        Aceitar
                      </div>
                    <% end %>
                  </div>
                  <div class="col-md-6 my-2 m-md-0">
                    <%= link_to  @invitation, method: :delete do %>
                      <h3 class="mdi mdi-trash-can-outline"></h3>
                      <div class="text-overline text-danger">
                        Ignora
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="pull-up">
      <div class="container" id="printableArea">
        <div class="row">
          <div class="col-md-12 m-b-40">
            <div class="card">
              <div class="card-body">
                <div class="row">
                  <div class="col-md-6">
                    <address class="m-t-10">
                      <%= @invitation.user.name%><br>
                      <span class="h4 font-primary"> você foi convidado á participar do meu evento, <%= @invitation.event.description%> </span>
                      <br>
                      Criado por <%= @invitation.event.user.name%> <br> criado em
                      <%= @invitation.event.created_at%> ate o dia <%= @invitation.event.data_event%> <br>


                    </address>
                  </div>
                </div>
                <div class="p-t-10 p-b-20">
                  <hr>
                  <div class="text-center opacity-75">
                    <button type="button" class="btn btn-event" data-toggle="modal"
                                        data-target="#slideRightModal">
                                   Mostra pessoas deste evento
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

<div class="modal fade modal-slide-right" id="slideRightModal" tabindex="-1" role="dialog" aria-labelledby="slideRightModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="slideRightModalLabel">Participantes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table align-td-middle table-card">
          <tbody>
          <% @invitation.select_users_by_events(@invitation.event.id).each do |event_user|%>
            <tr>
              <td>
                <div class="avatar avatar-sm ">
                  <i class="mdi mdi-account  mdi-48px"></i>
                </div>
              </td>
              <td><%= event_user.user.name %></td>
              <td><%= event_user.user.email %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>