config/routes.rb
Rails.application.routes.draw do

  resources :invitations
  resources :event_items
  resources :items
  resources :events
  devise_for :users

  delete 'exit_event/:id', to: 'events#exit_event', as: 'exit_event'
  get 'participating', to: 'events#participating', as: 'participating'
  get 'configs', to: 'user#configs', as: 'user_configs'
  patch 'configs', to: 'user#upload_avatar'
  get 'accept/invitation/:id', to: 'invitations#accept', as: 'accept_invities'
  get 'viewed_invitation/:id', to: 'invitations#viewed_invitation', as: 'viewed_invitation'
  patch 'event_item_status/:id', to: 'event_items#charge_status', as: 'charge_status'
  root to: 'dashboard#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
        resources :users, only: [:show, :create, :update, :destroy]
        resources :invitations
        resources :event_items
        resources :items
        resources :events
        get 'participating', to: 'events#participating'
        get 'configs', to: 'user#configs'
        patch 'configs', to: 'user#upload_avatar'
        get 'accept/invitation/:id', to: 'invitations#accept'
        get 'viewed_invitation/:id', to: 'invitations#viewed_invitation'
        get '/', to:'dashboard#index'
    end
  end
end

app/models/event_item.rb
class EventItem < ApplicationRecord
  belongs_to :event
  belongs_to :item
  validates_presence_of :quantities

  validate :verifi_item_exist_on_event, on: :create

  def verifi_item_exist_on_event
    item = EventItem.where(item_id: item_id, event_id: event_id).present?
    return if item == false

    errors.add(:Item, ' já existente no evento!')
  end

  def make_current_total(event_id)
    value_items = []
    event_item = EventItem.where(event_id: event_id)
    event_item.each do |event|
      value_items.push(event.item.value*event.quantities)
    end
    current_total_event = Event.find(event_id)
    current_total_event.update(total: value_items.sum)
  end

  def decrement_current_total(item_id)
    item_current_event = EventItem.find(item_id)
    event_current = Event.find(item_current_event.event_id)
    event_current.update(total: event_current.total - item_current_event.item.value)
  end
end

app/controllers/api/v1/event_items_controller.rb
# frozen_string_literal: true
module Api
  module V1
    class EventItemsController < BaseController
      include DeviseTokenAuth::Concerns::SetUserByToken
      before_action :authenticate_user!
      before_action :set_event_item, only: %i[show edit update destroy]

      # GET /event_items
      # GET /event_items.json
      def index
        @event_items = EventItem.all
      end

      # GET /event_items/1
      # GET /event_items/1.json
      def show
        @items = Item.where(user_id: current_user.id)
      end

      # GET /event_items/new
      def new
        @event_item = EventItem.new
      end

      # GET /event_items/1/edit
      def charge_status
        @event_item = EventItem.where(id: params[:id], item_id: params[:item_id]).take
        if @event_item.status
          if @event_item.update(status: false)
            flash[:success] = 'Item não comprado!'
            redirect_to event_path(@event_item.event.id)
          else
            flash[:error] = @event_item.errors.full_messages.to_sentence
            redirect_to event_path(@event_item.event.id)
          end
        else
          if @event_item.update(status: true)
            flash[:success] = 'Item comprado!'
            redirect_to event_path(@event_item.event.id)
          else
            flash[:error] = @event_item.errors.full_messages.to_sentence
            redirect_to event_path(@event_item.event.id)
          end
        end
      end

      # POST /event_items
      # POST /event_items.json
      def create
        @event_item = EventItem.new(event_item_params.merge(status: false))
        if @event_item.save
          EventItem.new.make_current_total(@event_item.event.id)
          flash[:success] = 'Item inserido!'
          redirect_to event_path(@event_item.event.id)
        else
          flash[:error] = @event_item.errors.full_messages.to_sentence
          redirect_to event_path(@event_item.event.id)
        end
      end

      # PATCH/PUT /event_items/1
      # PATCH/PUT /event_items/1.json
      def update
        respond_to do |format|
          if @event_item.update(event_item_params)
            format.html { redirect_to @event_item, notice: 'Event item was successfully updated.' }
            format.json { render :show, status: :ok, location: @event_item }
          else
            format.html { render :edit }
            format.json { render json: @event_item.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /event_items/1
      # DELETE /event_items/1.json
      def destroy
        EventItem.new.decrement_current_total(params[:id])
        @event_item.destroy
        flash[:success] = 'Item removido!'
        redirect_to event_path(@event_item.event.id)
      end

      private

      # Use callbacks to share common setup or constraints between actions.
      def set_event_item
        @event_item = EventItem.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def event_item_params
        params.require(:event_item).permit(:total, :status, :event_id, :item_id, :quantities)
      end
    end
  end
end

app/controllers/event_items_controller.rb
class EventItemsController < ApplicationController
  before_action :set_event_item, only: [:show, :edit, :update, :destroy]

  # GET /event_items
  # GET /event_items.json
  def index
    @event_items = EventItem.all
  end

  # GET /event_items/1
  # GET /event_items/1.json
  def show
    @items = Item.where(user_id: current_user.id)
  end

  # GET /event_items/new
  def new
    @event_item = EventItem.new
  end

  # GET /event_items/1/edit
  def charge_status
    @event_item = EventItem.where(id: params[:id], item_id: params[:item_id]).take
    if @event_item.status
      if @event_item.update(status: false)
        flash[:success] = 'Item não comprado!'
        redirect_to event_path(@event_item.event.id)
      else
        flash[:error] = @event_item.errors.full_messages.to_sentence
        redirect_to event_path(@event_item.event.id)
      end
    else
      if @event_item.update(status: true)
        flash[:success] = 'Item comprado!'
        redirect_to event_path(@event_item.event.id)
      else
        flash[:error] = @event_item.errors.full_messages.to_sentence
        redirect_to event_path(@event_item.event.id)
      end
    end
  end



  # POST /event_items
  # POST /event_items.json
  def create
    @event_item = EventItem.new(event_item_params.merge(status: false))
    if @event_item.save
      EventItem.new.make_current_total(@event_item.event.id)
      flash[:success] = 'Item inserido!'
      redirect_to event_path(@event_item.event.id)
    else
      flash[:error] = @event_item.errors.full_messages.to_sentence
      redirect_to event_path(@event_item.event.id)
    end
  end

  # PATCH/PUT /event_items/1
  # PATCH/PUT /event_items/1.json
  def update
    respond_to do |format|
      if @event_item.update(event_item_params)
        format.html { redirect_to @event_item, notice: 'Event item was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_item }
      else
        format.html { render :edit }
        format.json { render json: @event_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_items/1
  # DELETE /event_items/1.json
  def destroy
    EventItem.new.decrement_current_total(params[:id])
    @event_item.destroy
    flash[:success] = 'Item removido!'
    redirect_to event_path(@event_item.event.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_item
      @event_item = EventItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_item_params
      params.require(:event_item).permit(:total, :status, :event_id, :item_id, :quantities)
    end
end

app/helpers/event_items_helper.rb
module EventItemsHelper
end

app/views/event_items/_form.html.erb
<%= form_with(model: event_item, local: true) do |form| %>
  <%= form.hidden_field(:event_id, value: params[:id]) %>
<div class="row">
    <div class="col-md-5">
      <%= form.select(:item_id, @items.collect { |i| [i.description, i.id] }, {include_blank: "Selecione o item "}, class:'form-control form-control-lg select2')%>
    </div>

    <div class="col-6 form-group">
      <%= form.text_field :quantities, class:'form-control form-control-lg', placeholder: 'Quantidade' %>
    </div>
  </div>
  <div class="col-12 form-group">
    <%= form.submit 'Adicionar', class:'btn btn-success' %>
  </div>
<% end %>

app/views/event_items/edit.html.erb
<h1>Editing Event Item</h1>

<%= render 'form', event_item: @event_item %>

<%= link_to 'Show', @event_item %> |
<%= link_to 'Back', event_items_path %>

app/views/event_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Event Items</h1>

<table>
  <thead>
    <tr>
      <th>Total</th>
      <th>Status</th>
      <th>Event</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_items.each do |event_item| %>
      <tr>
        <td><%= event_item.total %></td>
        <td><%= event_item.status %></td>
        <td><%= event_item.event %></td>
        <td><%= event_item.item %></td>
        <td><%= link_to 'Show', event_item %></td>
        <td><%= link_to 'Edit', edit_event_item_path(event_item) %></td>
        <td><%= link_to 'Destroy', event_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event Item', new_event_item_path %>

app/views/event_items/new.html.erb
<h1>New Event Item</h1>

<%= render 'form', event_item: @event_item %>

<%= link_to 'Back', event_items_path %>

app/views/event_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total:</strong>
  <%= @event_item.total %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event_item.status %>
</p>

<p>
  <strong>Event:</strong>
  <%= @event_item.event %>
</p>

<p>
  <strong>Item:</strong>
  <%= @event_item.item %>
</p>

<%= link_to 'Edit', edit_event_item_path(@event_item) %> |
<%= link_to 'Back', event_items_path %>